name: easygo_frontend
description: "easyGO - Interurban Door-to-Door Travel Management and Luggage Tracking System."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^11.2.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/